"""TorchSim package base module."""

import os
from importlib.metadata import version
from pathlib import Path

import torch_sim._duecredit
from torch_sim import (
    autobatching,
    constraints,
    elastic,
    io,
    math,
    models,
    monte_carlo,
    neighbors,
    optimizers,
    quantities,
    runners,
    state,
    trajectory,
    transforms,
    units,
)
from torch_sim.autobatching import BinningAutoBatcher, InFlightAutoBatcher
from torch_sim.integrators import (
    INTEGRATOR_REGISTRY,
    Integrator,
    NVTNoseHooverState,
    nve_init,
    nve_step,
    nvt_langevin_init,
    nvt_langevin_step,
    nvt_nose_hoover_init,
    nvt_nose_hoover_invariant,
    nvt_nose_hoover_step,
    nvt_vrescale_init,
    nvt_vrescale_step,
)
from torch_sim.integrators.npt import (
    NPTLangevinAnisotropicState,
    NPTLangevinIsotropicState,
    NPTNoseHooverIsotropicState,
    npt_crescale_init,
    npt_crescale_isotropic_step,
    npt_crescale_triclinic_step,
    npt_langevin_anisotropic_init,
    npt_langevin_anisotropic_step,
    npt_langevin_isotropic_init,
    npt_langevin_isotropic_step,
    npt_nose_hoover_isotropic_init,
    npt_nose_hoover_isotropic_invariant,
    npt_nose_hoover_isotropic_step,
)
from torch_sim.monte_carlo import SwapMCState, swap_mc_init, swap_mc_step
from torch_sim.optimizers import (
    OPTIM_REGISTRY,
    BFGSState,
    FireState,
    LBFGSState,
    Optimizer,
    OptimState,
    bfgs_init,
    bfgs_step,
    fire_init,
    fire_step,
    gradient_descent_init,
    gradient_descent_step,
    lbfgs_init,
    lbfgs_step,
)
from torch_sim.optimizers.cell_filters import (
    CELL_FILTER_REGISTRY,
    CellBFGSState,
    CellFilter,
    CellFireState,
    CellLBFGSState,
    CellOptimState,
    get_cell_filter,
)
from torch_sim.plumed import PlumedModel
from torch_sim.properties.correlations import CorrelationCalculator
from torch_sim.quantities import (
    calc_kinetic_energy,
    calc_kT,
    calc_temperature,
    get_pressure,
    system_wise_max_force,
)
from torch_sim.runners import (
    generate_energy_convergence_fn,
    generate_force_convergence_fn,
    integrate,
    optimize,
    static,
)
from torch_sim.state import SimState, concatenate_states, initialize_state
from torch_sim.trajectory import TorchSimTrajectory, TrajectoryReporter


PKG_DIR = os.path.dirname(__file__)
ROOT = os.path.dirname(PKG_DIR)
SCRIPTS_DIR = f"{ROOT}/examples"
TORCH_SIM_CONFIG_DIR = Path.home() / ".torchsim"
TORCH_SIM_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

__version__ = version("torch-sim-atomistic")
__all__ = [
    "CELL_FILTER_REGISTRY",
    "INTEGRATOR_REGISTRY",
    "INTEGRATOR_REGISTRY",
    "OPTIM_REGISTRY",
    "OPTIM_REGISTRY",
    "BFGSState",
    "BinningAutoBatcher",
    "BinningAutoBatcher",
    "CellBFGSState",
    "CellFilter",
    "CellFireState",
    "CellLBFGSState",
    "CellOptimState",
    "CorrelationCalculator",
    "FireState",
    "InFlightAutoBatcher",
    "InFlightAutoBatcher",
    "Integrator",
    "Integrator",
    "LBFGSState",
    "NPTLangevinAnisotropicState",
    "NPTLangevinIsotropicState",
    "NPTNoseHooverIsotropicState",
    "NVTNoseHooverState",
    "NVTNoseHooverState",
    "OptimState",
    "Optimizer",
    "PlumedModel",
    "SimState",
    "SwapMCState",
    "SwapMCState",
    "TorchSimTrajectory",
    "TrajectoryReporter",
    "autobatching",
    "bfgs_init",
    "bfgs_step",
    "calc_kT",
    "calc_kinetic_energy",
    "calc_temperature",
    "concatenate_states",
    "constraints",
    "elastic",
    "fire_init",
    "fire_step",
    "generate_energy_convergence_fn",
    "generate_force_convergence_fn",
    "get_cell_filter",
    "get_pressure",
    "gradient_descent_init",
    "gradient_descent_step",
    "initialize_state",
    "integrate",
    "io",
    "lbfgs_init",
    "lbfgs_step",
    "math",
    "models",
    "monte_carlo",
    "neighbors",
    "npt_crescale_init",
    "npt_crescale_isotropic_step",
    "npt_crescale_triclinic_step",
    "npt_langevin_anisotropic_init",
    "npt_langevin_anisotropic_step",
    "npt_langevin_isotropic_init",
    "npt_langevin_isotropic_step",
    "npt_nose_hoover_isotropic_init",
    "npt_nose_hoover_isotropic_invariant",
    "npt_nose_hoover_isotropic_step",
    "nve_init",
    "nve_init",
    "nve_step",
    "nve_step",
    "nvt_langevin_init",
    "nvt_langevin_init",
    "nvt_langevin_step",
    "nvt_langevin_step",
    "nvt_nose_hoover_init",
    "nvt_nose_hoover_init",
    "nvt_nose_hoover_invariant",
    "nvt_nose_hoover_invariant",
    "nvt_nose_hoover_step",
    "nvt_nose_hoover_step",
    "nvt_vrescale_init",
    "nvt_vrescale_init",
    "nvt_vrescale_step",
    "nvt_vrescale_step",
    "optimize",
    "optimizers",
    "quantities",
    "runners",
    "state",
    "static",
    "swap_mc_init",
    "swap_mc_init",
    "swap_mc_step",
    "swap_mc_step",
    "system_wise_max_force",
    "trajectory",
    "transforms",
    "units",
]


import torch_sim._citations  # noqa: E402, F401
